{{- if .Values.httproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: query-module
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "query.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.httproute.gatewayName }}
  hostnames:
    - {{ .Values.httproute.hostname | quote }}
  rules:
    - matches:
        {{- range .Values.httproute.pathPrefixes }}
        - path:
            type: PathPrefix
            value: {{ . }}
        {{- end }}
      backendRefs:
        - name: query-module
          port: {{ .Values.port }}
{{- end }}
