apiVersion: v1
kind: Service
metadata:
  name: query-module
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "query.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "query.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
