apiVersion: v1
kind: Service
metadata:
  name: admin-module
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "admin.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "admin.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
