{{- if .Values.minio.httproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: minio-console
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "infra.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
  hostnames:
    - {{ .Values.minio.httproute.hostname | quote }}
  rules:
    - backendRefs:
        - name: minio
          port: {{ .Values.minio.portConsole }}
{{- end }}
