apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "infra.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.externalPostgres.user }}
  DB_PASSWORD: {{ .Values.externalPostgres.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "infra.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.externalRedis.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "infra.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.rootUser }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.rootPassword }}
  STORAGE_S3_ACCESS_KEY_ID: {{ .Values.minio.rootUser }}
  STORAGE_S3_SECRET_ACCESS_KEY: {{ .Values.minio.rootPassword }}
